Extract posterior tip of the discs during level extraction
neuropoly/totalspineseg pull request #76
Opened 2024-10-16 14:06 UTC by NathanMolinier

## Description

This PR replaces the current discs label projection with an extraction of the posterior tip of the discs. The idea is to align the model with the spinalcordtoolbox convention to simplify the futur integration.

The extraction of the level 1 and 2 was also modified to be more precise and robust.

2024-10-20 13:32 UTC, yw7 requested changes

2024-11-04 21:25 UTC, NathanMolinier commented on totalspineseg/inference.py
>          disc_labels=list(range(63, 68)) + list(range(71, 83)) + list(range(91, 96)) + [100],
Should we create a separate short PR to make sure it doesn't create problems ?

2024-11-04 21:34 UTC, NathanMolinier commented on totalspineseg/utils/extract_levels.py
> +            # The coordinate of 1 needs to be in the same slice as 3 but below the max index of C1
<img width="233" alt="Screenshot 2024-11-04 at 16 32 08" src="https://github.com/user-attachments/assets/bc30e174-d2f0-48fa-ace9-3c2f5044688d">

In the convention, the label 1 is at the top of C2. And I found that setting this limitation provided the best output.

2024-11-04 21:36 UTC, NathanMolinier commented on totalspineseg/utils/extract_levels.py
> +    # If C2-C3 and C1 are in the segmentation, set 1 and 2
I projected 2 on the anteriorline, I think it is good now no ?

2024-11-04 21:38 UTC, NathanMolinier commented on totalspineseg/utils/extract_levels.py
> -        if (c1_label > 0 and c1_label in seg_data) or (c1_label == 0 and canal_superior_index[2] - c2c3_index[2] >= 8 and output_seg_data.shape[2] - canal_superior_index[2] >= 2):
I don't think so because I added this check:
```
if c1_label in seg_data:
```
1 and 2 will only be added if C1 is visible

2024-11-04 21:45 UTC, NathanMolinier commented
> A few points to discuss before merging:
> 
> 1. Mentioning out why label 1 is not projected on the anterior line.

I added this commit [6f9bc4a](https://github.com/neuropoly/totalspineseg/pull/76/commits/6f9bc4afc121060b06e88701386e80ea841c76e9) to mention the followed convention.

> 2. Regarding label 2 - Should it be projected to the centerline/anterior line? Should we put it on inferior projection of C1 on anterior line - this will prevent wrong labels where the image contain only part of C1/C2 like in some T2star images for example.

I project the label 2 on the anterior line now. I think it should work correctly now.

> 3. How do we address if more then one voxel in the anterior line have the same minimum distance from the disc, or more the one voxel is at the top of C2 (We can also leave it for future PR since clearly this PR improve current implemetation and not change the strategy of taking the first).

It should not be a problem, any point could work. Let's see in the future if it raises issues.

> 4. How do we address cases where only part of C2 is seen in the image.

We don't add 1 and 2.

> 5. Regarding putting labels 1 and 2 on the same alice (in x axis) as label 3 - what about cases where the image is not align with the x axis? projecting label 1 on anterior line is also not a good practice since sometime the superior voxel of the anterior line is not in the mid sagital slice of the canal. Maybe put is in the same slce as label 2 will be better? and we can project label 2 on the anterior line of the canal.

I'm not sure I understand the problem since we know the orientation before applying the function.

2024-11-19 01:09 UTC, msclab20 commented
There is an error for some images with some error voxels of C2 around C1. For other images seem to work very well!

for example:
sub-milanMarcella001_T1w:
![sub-milanMarcella001_T1w_sag_0 5](https://github.com/user-attachments/assets/9d148ab6-9b3e-48de-9261-b1c48c5bb7a1)

sub-zurichMPM01_ses-01_echo-1_T1w:
![sub-zurichMPM01_ses-01_echo-1_T1w_sag_0 5](https://github.com/user-attachments/assets/c229fc5d-4613-4016-ad21-0dc1656f1b89)

2024-11-19 15:13 UTC, NathanMolinier commented
Yes or maybe we could also project 1 on the anterior line

2024-11-19 15:51 UTC, NathanMolinier commented
Now every label is being projected onto the anteriorline to have more robust outputs

2024-11-20 15:02 UTC, NathanMolinier commented
Since we now project every voxels onto the centerline, we thought about getting rid of the use of the label C2. However, because the canal segmentation is stopping at the top of C1, for some subjects, projecting the 1 coordinate onto the anterior line was not accurate. For this reason, we used the Z maximum coordinate of C2 that is below the Z maximum of C1 and projected this point onto the anterior line. Because this new point is below the end of the segmentation, the projection is generally more accurate.
|Project max z of C1|Project max z of C2 below max z of C1|
|:---:|:---:|
|![sub-247090_acq-sagittal_T2w_sag_0 5_step1_levels_tags](https://github.com/user-attachments/assets/456938f7-a826-4289-87b4-be432eedf77f)|![sub-247090_acq-sagittal_T2w_sag_0 5_step1_levels_tags](https://github.com/user-attachments/assets/21205226-9828-4e3a-96d9-27975c6e15d9)|

2024-11-20 16:04 UTC, yw7 approved these changes

2024-11-20 16:06 UTC, yw7 commented
Tested and work well!! Great improvement from thte previous implementation

2024-11-20 16:17 UTC, merged